---
- name: Create directory for scripts
  ansible.builtin.file:
    path: /etc/zabbix/scripts
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Include ./nginx.yml
  when: "'nginx' in ansible_facts.packages"
  ansible.builtin.import_tasks: nginx.yml
  tags:
    - nginx_zabbix_agent2
